import { assert } from "chai";
import {
  hasMarkdownAttachment,
  resolvePdfAttachment,
} from "../src/modules/pdfAttachmentResolver";

describe("pdfAttachmentResolver", function () {
  afterEach(function () {
    delete (globalThis as any).Zotero;
  });

  it("returns the first PDF attachment with an existing file path", async function () {
    const pdfAttachment = createAttachment({
      contentType: "application/pdf",
      filePath: "C:\\papers\\a.pdf",
    });
    const htmlAttachment = createAttachment({
      contentType: "text/html",
      filePath: "C:\\papers\\a.html",
    });
    const item = createItem([1, 2]);

    (globalThis as any).Zotero = {
      Items: {
        getAsync: async () => [htmlAttachment, pdfAttachment],
      },
    };

    const result = await resolvePdfAttachment(item as Zotero.Item);

    assert.equal(result.attachment, pdfAttachment);
    assert.equal(result.filePath, "C:\\papers\\a.pdf");
  });

  it("throws when the item has no PDF attachment", async function () {
    const item = createItem([1]);

    (globalThis as any).Zotero = {
      Items: {
        getAsync: async () => [
          createAttachment({
            contentType: "text/html",
            filePath: "C:\\papers\\a.html",
          }),
        ],
      },
    };

    try {
      await resolvePdfAttachment(item as Zotero.Item);
      assert.fail("Expected resolvePdfAttachment to throw");
    } catch (error) {
      assert.match(String(error), /No PDF attachment found/);
    }
  });

  it("ignores untagged markdown attachments", function () {
    const item = createItem([1, 2]);
    const markdownAttachment = createAttachment({
      contentType: "text/plain",
      filename: "paper.md",
    });

    (globalThis as any).Zotero = {
      Items: {
        get: (id: number) =>
          id === 1
            ? createAttachment({ contentType: "application/pdf" })
            : markdownAttachment,
      },
    };

    assert.isFalse(hasMarkdownAttachment(item as Zotero.Item));
  });

  it("detects markdown attachments generated by this plugin", function () {
    const item = createItem([1, 2]);
    const markdownAttachment = createAttachment({
      contentType: "text/plain",
      filename: "paper.md",
      tags: ["zotero-pdf-to-markdown"],
    });

    (globalThis as any).Zotero = {
      Items: {
        get: (id: number) =>
          id === 1
            ? createAttachment({ contentType: "application/pdf" })
            : markdownAttachment,
      },
    };

    assert.isTrue(hasMarkdownAttachment(item as Zotero.Item));
  });
});

function createItem(attachmentIDs: number[]) {
  return {
    getAttachments: () => attachmentIDs,
  };
}

function createAttachment(options: {
  contentType: string;
  filename?: string;
  filePath?: string | false;
  tags?: string[];
}) {
  return {
    isAttachment: () => true,
    attachmentContentType: options.contentType,
    attachmentFilename: options.filename ?? "attachment.bin",
    getFilePathAsync: async () => options.filePath ?? false,
    hasTag: (tag: string) => options.tags?.includes(tag) ?? false,
  };
}
