// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "zhiyiApiUrl": string;
      "zhiyiApiKey": string;
      "zhiyiTableMode": string;
      "zhiyiFormulaFormat": string;
      "zhiyiEnableCrossPageMerge": boolean;
      "picgoUploadUrl": string;
      "picgoSecret": string;
      "picgoUploadIntervalMs": number;
      "skipUrlPrefixes": string;
      "markdownFilenameTemplate": string;
      "existingMarkdownStrategy": string;
    };
  }
}
