// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "pdfParserProvider": string;
      "zhiyiApiUrl": string;
      "zhiyiApiKey": string;
      "zhiyiTableMode": string;
      "zhiyiFormulaFormat": string;
      "zhiyiEnableCrossPageMerge": boolean;
      "mineruApiUrl": string;
      "mineruApiToken": string;
      "mineruModelVersion": string;
      "mineruLanguage": string;
      "mineruEnableTable": boolean;
      "mineruIsOcr": boolean;
      "mineruEnableFormula": boolean;
      "mineruPageRanges": string;
      "enablePicgoUpload": boolean;
      "picgoUploadUrl": string;
      "picgoSecret": string;
      "picgoUploadIntervalMs": number;
      "skipUrlPrefixes": string;
      "markdownFilenameTemplate": string;
      "existingMarkdownStrategy": string;
    };
  }
}
