// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "pdfParserProvider": string;
      "zhiyiApiUrl": string;
      "zhiyiApiKey": string;
      "zhiyiTableMode": string;
      "zhiyiFormulaFormat": string;
      "zhiyiEnableCrossPageMerge": string;
      "mineruApiUrl": string;
      "mineruApiToken": string;
      "mineruModelVersion": string;
      "mineruLanguage": string;
      "mineruEnableTable": string;
      "mineruIsOcr": string;
      "mineruEnableFormula": string;
      "mineruPageRanges": string;
      "glmOcrApiUrl": string;
      "glmOcrApiKey": string;
      "glmOcrReturnCropImages": string;
      "glmOcrNeedLayoutVisualization": string;
      "glmOcrStartPageId": number;
      "glmOcrEndPageId": number;
      "glmOcrMaxFileSizeMb": number;
      "enablePicgoUpload": string;
      "picgoUploadUrl": string;
      "picgoSecret": string;
      "skipUrlPrefixes": string;
      "markdownFilenameTemplate": string;
    };
  }
}
